In [1]:
import pandas as pd
import numpy as np

In [2]:
covid = pd.read_csv('dados/SUS/COVIDBR_2023_17jan2023.csv', sep=';')
eleicao18 = pd.read_csv('dados/TSE/2018_Bolsonaro.csv', sep=';')
eleicao22 = pd.read_csv('dados/TSE/2022_Bolsonaro.csv', sep=';')

In [3]:
covid = covid[['regiao', 'estado', 'municipio', 'data']]
covid = covid[covid['data'] == '2023-01-17']
covid = covid[~((covid.estado.isna()) | (covid.municipio.isna()))]
covid.reset_index(inplace=True)
covid = covid.drop(columns = ['index', 'data'])
covid['municipio_estado'] = (covid.municipio + ' / ' + covid.estado)
covid

            regiao estado              municipio            municipio_estado
0            Norte     RO  Alta Floresta D'Oeste  Alta Floresta D'Oeste / RO
1            Norte     RO              Ariquemes              Ariquemes / RO
2            Norte     RO                 Cabixi                 Cabixi / RO
3            Norte     RO                 Cacoal                 Cacoal / RO
4            Norte     RO             Cerejeiras             Cerejeiras / RO
...            ...    ...                    ...                         ...
5565  Centro-Oeste     GO             Vianópolis             Vianópolis / GO
5566  Centro-Oeste     GO         Vicentinópolis         Vicentinópolis / GO
5567  Centro-Oeste     GO               Vila Boa               Vila Boa / GO
5568  Centro-Oeste     GO          Vila Propício          Vila Propício / GO
5569  Centro-Oeste     DF               Brasília               Brasília / DF

[5570 rows x 4 columns]

In [4]:
import unicodedata

In [5]:
for i in range(len(covid.municipio_estado)):
    covid.municipio_estado[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', covid.municipio_estado[i].upper())
        if not unicodedata.combining(ch))

covid

            regiao estado              municipio            municipio_estado
0            Norte     RO  Alta Floresta D'Oeste  ALTA FLORESTA D'OESTE / RO
1            Norte     RO              Ariquemes              ARIQUEMES / RO
2            Norte     RO                 Cabixi                 CABIXI / RO
3            Norte     RO                 Cacoal                 CACOAL / RO
4            Norte     RO             Cerejeiras             CEREJEIRAS / RO
...            ...    ...                    ...                         ...
5565  Centro-Oeste     GO             Vianópolis             VIANOPOLIS / GO
5566  Centro-Oeste     GO         Vicentinópolis         VICENTINOPOLIS / GO
5567  Centro-Oeste     GO               Vila Boa               VILA BOA / GO
5568  Centro-Oeste     GO          Vila Propício          VILA PROPICIO / GO
5569  Centro-Oeste     DF               Brasília               BRASILIA / DF

[5570 rows x 4 columns]

In [6]:
eleicao18

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,5165
1,AC,ASSIS BRASIL,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,2333
2,AC,BRASILÉIA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,8711
3,AC,BUJARI,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,4676
4,AC,CAPIXABA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,3895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5703,ZZ,WELLINGTON,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,179
5704,ZZ,WINDHOEK,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,11
5705,ZZ,XANGAI,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,151
5706,ZZ,ZAGREB,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,8
5707,ZZ,ZURIQUE,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,2948

In [7]:
eleicao22

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,5317
1,AC,ASSIS BRASIL,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,2717
2,AC,BRASILÉIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,9593
3,AC,BUJARI,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,4693
4,AC,CAPIXABA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,3963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746,ZZ,WINDHOEK,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,31
5747,ZZ,XANGAI,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,62
5748,ZZ,YANGON,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,0
5749,ZZ,ZAGREB,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,15
5750,ZZ,ZURIQUE,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,2762

In [8]:
eleicao18 = eleicao18[['sg_uf','nm_municipio']]
eleicao22 = eleicao22[['sg_uf','nm_municipio']]
eleicao18['municipio_estado'] = eleicao18.nm_municipio + ' / ' + eleicao18.sg_uf
eleicao22['municipio_estado'] = eleicao22.nm_municipio + ' / ' + eleicao22.sg_uf
eleicao18 = eleicao18[eleicao18.sg_uf != 'ZZ']
eleicao22 = eleicao22[eleicao22.sg_uf != 'ZZ']
eleicao18.columns = ['uf_18', 'mun_18', 'mun_est_18']
eleicao22.columns = ['uf_22', 'mun_22', 'mun_est_22']

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_100576\3904930239.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eleicao18['municipio_estado'] = eleicao18.nm_municipio + ' / ' + eleicao18.sg_uf
C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_100576\3904930239.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eleicao22['municipio_estado'] = eleicao22.nm_municipio + ' / ' + eleicao22.sg_uf

In [9]:
for i in range(len(eleicao18.mun_est_18)):
    eleicao18.mun_est_18[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', eleicao18.mun_est_18[i]).upper() 
        if not unicodedata.combining(ch))


for i in range(len(eleicao22.mun_est_22)):
    eleicao22.mun_est_22[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', eleicao22.mun_est_22[i]).upper() 
        if not unicodedata.combining(ch))

In [10]:
covid = covid.sort_values(by='municipio_estado')
covid.reset_index(inplace=True)
covid = covid.drop(columns=['index'])

eleicao18 = eleicao18.sort_values(by='mun_est_18')
eleicao18.reset_index(inplace=True)
eleicao18 = eleicao18.drop(columns=['index'])

eleicao22 = eleicao22.sort_values(by='mun_est_22')
eleicao22.reset_index(inplace=True)
eleicao22 = eleicao22.drop(columns=['index'])

In [11]:
dados = pd.DataFrame(columns=['covid', 'eleicao18', 'eleicao22'])

In [12]:
dados['covid'] = covid.municipio_estado
dados['eleicao18'] = eleicao18.mun_est_18
dados['eleicao22'] = eleicao22.mun_est_22

In [13]:
dados

,covid,eleicao18,eleicao22
0,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO
1,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG
2,ABADIANIA / GO,ABADIANIA / GO,ABADIANIA / GO
3,ABAETE / MG,ABAETE / MG,ABAETE / MG
4,ABAETETUBA / PA,ABAETETUBA / PA,ABAETETUBA / PA
...,...,...,...
5565,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA
5566,ZABELE / PB,ZABELE / PB,ZABELE / PB
5567,ZACARIAS / SP,ZACARIAS / SP,ZACARIAS / SP
5568,ZE DOCA / MA,ZE DOCA / MA,ZE DOCA / MA
5569,ZORTEA / SC,ZORTEA / SC,ZORTEA / SC

### Optei por levar todos os nomes para o dado mais atual - 'eleicao22'

In [14]:
lista_22 = dados.eleicao22.to_list()
lista_18 = dados.eleicao18.to_list()
lista_cov = dados.covid.to_list()

In [15]:
dados['corr_covid'] = (~dados['covid'].isin(lista_22)).astype(int)
dados['22_covid'] = (~dados['eleicao22'].isin(lista_cov)).astype(int)

dados['corr_18'] = (~dados['eleicao18'].isin(lista_22)).astype(int)
dados['22_18'] = (~dados['eleicao22'].isin(lista_18)).astype(int)

dados['covid_18'] = (~dados['eleicao18'].isin(lista_cov)).astype(int)
dados['18_covid'] = (~dados['covid'].isin(lista_18)).astype(int)

In [16]:
dados['corrigir'] = dados['corr_covid'] + dados['22_covid'] + dados['corr_18'] + dados['22_18'] + dados['covid_18'] + dados['18_covid']

In [17]:
dados[dados['corrigir'] != 0]

,covid,eleicao18,eleicao22,corr_covid,22_covid,corr_18,22_18,covid_18,18_covid,corrigir
28,ACU / RN,ACUCENA / MG,ACUCENA / MG,1,0,0,0,0,1,2
179,ALVORADA D'OESTE / RO,ALVORADA DO GURGUEIA / PI,ALVORADA DO GURGUEIA / PI,1,0,0,0,0,1,2
181,ALVORADA DO GURGUEIA / PI,ALVORADA DO OESTE / RO,ALVORADA DO OESTE / RO,0,1,0,0,1,0,2
375,ARENOPOLIS / GO,ARES / RN,AREZ / RN,0,1,1,1,0,0,3
376,ARES / RN,ARGIRITA / MG,ARGIRITA / MG,1,0,0,0,0,0,1
411,ASSIS CHATEAUBRIAND / PR,ASSU / RN,ASSU / RN,0,1,0,0,1,0,2
638,BOA VENTURA / PB,BOA SAUDE / RN,BOA SAUDE / RN,0,1,0,0,1,0,2
913,CAMACAN / BA,CALUMBI / PE,CALUMBI / PE,1,0,0,0,0,1,2
914,CAMACARI / BA,CAMACA / BA,CAMACA / BA,0,1,0,0,1,0,2
1608,DONA EUZEBIA / MG,DONA EMMA / SC,DONA EMMA / SC,1,0,0,0,0,1,2
1609,DONA FRANCISCA / RS,DONA EUSEBIA / MG,DONA EUSEBIA / MG,0,1,0,0,1,0,2
1646,ELDORADO DO CARAJAS / PA,ELDORADO / SP,ELDORADO / SP,1,0,0,0,0,1,2
1648,ELESBAO VELOSO / PI,ELDORADO DOS CARAJAS / PA,ELDORADO DOS CARAJAS / PA,0,1,0,0,1,0,2
1701,ESPIGAO D'OESTE / RO,ESPIGAO ALTO DO IGUACU / PR,ESPIGAO ALTO DO IGUACU / PR,1,0,0,0,0,1,2
1702,ESPINOSA / MG,ESPIGAO DO OESTE / RO,ESPIGAO DO OESTE / RO,0,1,0,0,1,0,2
1834,FORTALEZA DOS VALOS / RS,FORTALEZA DO TABOCAO / TO,FORTALEZA DOS NOGUEIRAS / MA,0,0,1,0,1,0,2
1955,GRACHO CARDOSO / SE,GRACA / CE,GRACA ARANHA / MA,1,0,0,0,0,1,2
1956,GRAJAU / MA,GRACA ARANHA / MA,GRACCHO CARDOSO / SE,0,1,0,0,0,0,1
1957,GRAMADO / RS,GRACCHO CARDOSO / SE,GRAJAU / MA,0,0,0,0,1,0,1
1965,GRAO PARA / SC,GRANJEIRO / CE,GRAO MOGOL / MG,1,0,0,0,0,1,2
1966,GRAVATA / PE,GRAO MOGOL / MG,GRAO-PARA / SC,0,1,0,0,0,0,1
1967,GRAVATAI / RS,GRAO-PARA / SC,GRAVATA / PE,0,0,0,0,1,0,1
2518,JANUARIO CICCO / RN,JANIOPOLIS / PR,JANUARIA / MG,1,0,0,0,0,1,2
3441,OLHOS-D'AGUA / MG,OLHO D'AGUA GRANDE / AL,OLHOS D'AGUA / MG,1,1,0,0,0,1,3
3442,OLIMPIA / SP,OLHOS D'AGUA / MG,OLIMPIA / SP,0,0,0,0,1,0,1
4078,QUIJINGUE / BA,QUEVEDOS / RS,QUIJINGUE / BA,0,0,0,1,0,1,2
4080,QUINTA DO SOL / PR,QUINJINGUE / BA,QUINTA DO SOL / PR,0,0,1,0,1,0,2
4410,SANTA ISABEL DO RIO NEGRO / AM,SANTA ISABEL DO IVAI / PR,SANTA ISABEL DO PARA / PA,0,1,0,0,0,0,1
4411,SANTA IZABEL DO OESTE / PR,SANTA ISABEL DO PARA / PA,SANTA ISABEL DO RIO NEGRO / AM,0,0,0,0,1,0,1
4412,SANTA IZABEL DO PARA / PA,SANTA ISABEL DO RIO NEGRO / AM,SANTA IZABEL DO OESTE / PR,1,0,0,0,0,1,2
4812,SAO LUIS DO PIAUI / PI,SAO LUIS DO CURU / CE,SAO LUIS DO PARAITINGA / SP,0,1,0,0,0,0,1
4813,SAO LUIS DO QUITUNDE / AL,SAO LUIS DO PARAITINGA / SP,SAO LUIS DO PIAUI / PI,0,0,0,0,1,0,1
4817,SAO LUIZ DO PARAITINGA / SP,SAO LUIZ / RR,SAO LUIZ DO NORTE / GO,1,0,0,0,0,1,2
4908,SAO TIAGO / MG,SAO SIMAO / SP,SAO THOME DAS LETRAS / MG,0,1,0,0,0,0,1
4909,SAO TOMAS DE AQUINO / MG,SAO THOME DAS LETRAS / MG,SAO TIAGO / MG,0,0,0,0,1,0,1
4912,SAO TOME DAS LETRAS / MG,SAO TOME / PR,SAO TOME / RN,1,0,0,0,0,1,2
4960,SEM-PEIXE / MG,SELVIRIA / MS,SEM PEIXE / MG,1,1,0,0,0,1,3
4961,SENA MADUREIRA / AC,SEM PEIXE / MG,SENA MADUREIRA / AC,0,0,0,0,1,0,1
5113,TABOCAO / TO,TABOAO DA SERRA / SP,TABOCAO / TO,0,0,0,1,0,1,2

covid	

corretor = list(['ASSU',
  'ALVORADA DO OESTE',
  'AREZ',
  'BOA SAUDE',
  'CAMACA',
  'DONA EUSEBIA',
  'ELDORADO DOS CARAJAS',
  'ESPIGAO DO OESTE',
  'GRACCHO CARDOSO',
  'GRAO-PARA',
  "OLHOS D'AGUA",
  'SANTA ISABEL DO PARA',
  'SAO LUIS DO PARAITINGA',
  'SAO THOME DAS LETRAS',
  'SEM PEIXE'
])

trocas = list(['ACU',
    'ALVORADA D'OESTE',
    'ARES',
    'JANUARIO CICCO',
    'CAMACAN',
    'DONA EUZEBIA',
    'ELDORADO DO CARAJAS',
    'ESPIGAO D'OESTE',
    'GRACHO CARDOSO',
    'GRAO PARA',
    'OLHOS-D'AGUA',
    'SANTA IZABEL DO PARA',
    'SAO LUIZ DO PARAITINGA',
    'SAO TOME DAS LETRAS',
    'SEM-PEIXE
])


eleicao18	

corretor = list(['AREZ',
  'TABOCAO',
  'QUIJINGUE'
])

trocas = list(['ARES'
  'FORTALEZA DO TABOCAO'
  'QUINJINGUE'
])

eleicao22

### Verificação após as correções (Rodar nos arquivos salvos)

In [18]:
n_covid = pd.read_csv('arquivos/covid_municipios.csv')
n_eleicao18 = pd.read_csv('arquivos/eleicao18.csv')
n_eleicao22 = pd.read_csv('arquivos/eleicao22.csv')

In [19]:
n_covid['municipio_estado'] = n_covid['municipio'] + ' / ' + n_covid['estado']
n_eleicao18['municipio_estado'] = n_eleicao18['municipio'] + ' / ' + n_eleicao18['estado']
n_eleicao22['municipio_estado'] = n_eleicao22['municipio'] + ' / ' + n_eleicao22['estado']

In [20]:
n_eleicao18 = n_eleicao18[n_eleicao18['estado'] != 'ZZ']
n_eleicao22 = n_eleicao22[n_eleicao22['estado'] != 'ZZ']

In [21]:
n_covid = n_covid.sort_values(by='municipio_estado')
n_covid.reset_index(inplace=True)
n_covid = n_covid.drop(columns=['index'])

n_eleicao18 = n_eleicao18.sort_values(by='municipio_estado')
n_eleicao18.reset_index(inplace=True)
n_eleicao18 = n_eleicao18.drop(columns=['index'])

n_eleicao22 = n_eleicao22.sort_values(by='municipio_estado')
n_eleicao22.reset_index(inplace=True)
n_eleicao22 = n_eleicao22.drop(columns=['index'])

In [22]:
n_dados = pd.DataFrame(columns=['covid', 'eleicao18', 'eleicao22'])

In [23]:
n_dados.covid = n_covid.municipio_estado
n_dados.eleicao18 = n_eleicao18.municipio_estado
n_dados.eleicao22 = n_eleicao22.municipio_estado

In [24]:

n_dados

,covid,eleicao18,eleicao22
0,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO
1,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG
2,ABADIANIA / GO,ABADIANIA / GO,ABADIANIA / GO
3,ABAETE / MG,ABAETE / MG,ABAETE / MG
4,ABAETETUBA / PA,ABAETETUBA / PA,ABAETETUBA / PA
...,...,...,...
5565,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA
5566,ZABELE / PB,ZABELE / PB,ZABELE / PB
5567,ZACARIAS / SP,ZACARIAS / SP,ZACARIAS / SP
5568,ZE DOCA / MA,ZE DOCA / MA,ZE DOCA / MA
5569,ZORTEA / SC,ZORTEA / SC,ZORTEA / SC

In [25]:
lista_22 = n_dados.eleicao22.to_list()
lista_18 = n_dados.eleicao18.to_list()
lista_cov = n_dados.covid.to_list()

n_dados['corr_covid'] = (~n_dados['covid'].isin(lista_22)).astype(int)
n_dados['22_covid'] = (~n_dados['eleicao22'].isin(lista_cov)).astype(int)

n_dados['corr_18'] = (~n_dados['eleicao18'].isin(lista_22)).astype(int)
n_dados['22_18'] = (~n_dados['eleicao22'].isin(lista_18)).astype(int)

n_dados['covid_18'] = (~n_dados['eleicao18'].isin(lista_cov)).astype(int)
n_dados['18_covid'] = (~n_dados['covid'].isin(lista_18)).astype(int)

n_dados['corrigir'] = n_dados['corr_covid'] + n_dados['22_covid'] + n_dados['corr_18'] + n_dados['22_18'] + n_dados['covid_18'] + n_dados['18_covid']

n_dados

,covid,eleicao18,eleicao22,corr_covid,22_covid,corr_18,22_18,covid_18,18_covid,corrigir
0,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO,ABADIA DE GOIAS / GO,0,0,0,0,0,0,0
1,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG,ABADIA DOS DOURADOS / MG,0,0,0,0,0,0,0
2,ABADIANIA / GO,ABADIANIA / GO,ABADIANIA / GO,0,0,0,0,0,0,0
3,ABAETE / MG,ABAETE / MG,ABAETE / MG,0,0,0,0,0,0,0
4,ABAETETUBA / PA,ABAETETUBA / PA,ABAETETUBA / PA,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
5565,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA,XIQUE-XIQUE / BA,0,0,0,0,0,0,0
5566,ZABELE / PB,ZABELE / PB,ZABELE / PB,0,0,0,0,0,0,0
5567,ZACARIAS / SP,ZACARIAS / SP,ZACARIAS / SP,0,0,0,0,0,0,0
5568,ZE DOCA / MA,ZE DOCA / MA,ZE DOCA / MA,0,0,0,0,0,0,0
5569,ZORTEA / SC,ZORTEA / SC,ZORTEA / SC,0,0,0,0,0,0,0

In [26]:

n_dados[n_dados['corrigir'] != 0]

Empty DataFrame
Columns: [covid, eleicao18, eleicao22, corr_covid, 22_covid, corr_18, 22_18, covid_18, 18_covid, corrigir]
Index: []