In [1]:
import pandas as pd
import numpy as np

In [2]:
dadosJair = pd.read_csv('DADOS/TSE/2018_Bolsonaro.csv', sep=';')
dadosHaddad = pd.read_csv('DADOS/TSE/2018_Haddad.csv', sep=';')

In [3]:
dadosJair

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,5165
1,AC,ASSIS BRASIL,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,2333
2,AC,BRASILÉIA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,8711
3,AC,BUJARI,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,4676
4,AC,CAPIXABA,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,3895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5703,ZZ,WELLINGTON,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,179
5704,ZZ,WINDHOEK,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,11
5705,ZZ,XANGAI,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,151
5706,ZZ,ZAGREB,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,8
5707,ZZ,ZURIQUE,1,Presidente,17,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PSL,PSL / PRTB,2,Eleito,2019-02-27 18:15:58,BR,280000614517,Válido,2022802018,2948

In [4]:
dadosHaddad

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,1300
1,AC,ASSIS BRASIL,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,1660
2,AC,BRASILÉIA,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,3208
3,AC,BUJARI,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,1274
4,AC,CAPIXABA,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,1086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5703,ZZ,WELLINGTON,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,128
5704,ZZ,WINDHOEK,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,7
5705,ZZ,XANGAI,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,48
5706,ZZ,ZAGREB,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,5
5707,ZZ,ZURIQUE,1,Presidente,13,FERNANDO HADDAD,FERNANDO HADDAD,PT,PT / PC do B / PROS,2,Não Eleito,2019-02-27 18:15:58,BR,280000629808,Válido,2022802018,1835

In [5]:
verificador = dadosHaddad.describe().qt_votos_nom_validos

In [6]:
dadosJair.columns

Index(['sg_uf', 'nm_municipio', 'cd_cargo', 'ds_cargo', 'nr_candidato',
       'nm_candidato', 'nm_urna_candidato', 'sg_partido',
       'ds_composicao_coligacao', 'nr_turno', 'ds_sit_totalizacao',
       'dt_ult_totalizacao', 'sg_ue', 'sq_candidato',
       'nm_tipo_destinacao_votos', 'sq_eleicao_divulga',
       'qt_votos_nom_validos'],
      dtype='object')

In [7]:
dados = dadosJair[['sg_uf', 'nm_municipio', 'qt_votos_nom_validos']]

In [8]:
dados.columns = ['estado', 'municipio_0', 'votos_Bolsonaro']

In [9]:
dados['votos_Haddad'] = 0
dados

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\647790237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['votos_Haddad'] = 0

     estado   municipio_0  votos_Bolsonaro  votos_Haddad
0        AC    ACRELÂNDIA             5165             0
1        AC  ASSIS BRASIL             2333             0
2        AC     BRASILÉIA             8711             0
3        AC        BUJARI             4676             0
4        AC      CAPIXABA             3895             0
...     ...           ...              ...           ...
5703     ZZ    WELLINGTON              179             0
5704     ZZ      WINDHOEK               11             0
5705     ZZ        XANGAI              151             0
5706     ZZ        ZAGREB                8             0
5707     ZZ       ZURIQUE             2948             0

[5708 rows x 4 columns]

In [10]:
for i in range(dadosHaddad.shape[0]):
    if dados.estado[i] == dadosHaddad.sg_uf[i]:
        dados.votos_Haddad[i] = (dadosHaddad.qt_votos_nom_validos[i])

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\2889401891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.votos_Haddad[i] = (dadosHaddad.qt_votos_nom_validos[i])

In [11]:
dados

     estado   municipio_0  votos_Bolsonaro  votos_Haddad
0        AC    ACRELÂNDIA             5165          1300
1        AC  ASSIS BRASIL             2333          1660
2        AC     BRASILÉIA             8711          3208
3        AC        BUJARI             4676          1274
4        AC      CAPIXABA             3895          1086
...     ...           ...              ...           ...
5703     ZZ    WELLINGTON              179           128
5704     ZZ      WINDHOEK               11             7
5705     ZZ        XANGAI              151            48
5706     ZZ        ZAGREB                8             5
5707     ZZ       ZURIQUE             2948          1835

[5708 rows x 4 columns]

In [12]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5708 entries, 0 to 5707
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   estado           5708 non-null   object
 1   municipio_0      5708 non-null   object
 2   votos_Bolsonaro  5708 non-null   int64
 3   votos_Haddad     5708 non-null   int64
dtypes: int64(2), object(2)
memory usage: 178.5+ KB

In [13]:
dados.describe().votos_Haddad == verificador

count    True
mean     True
std      True
min      True
25%      True
50%      True
75%      True
max      True
dtype: bool

In [14]:
dados['regiao'] = ''

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\1577613325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['regiao'] = ''

In [15]:
regiao = {'RO':	'Norte',
'AC': 'Norte',
'AM': 'Norte',
'RR': 'Norte',
'PA': 'Norte',
'AP': 'Norte',
'TO': 'Norte',
'MA': 'Nordeste',
'PI': 'Nordeste',
'CE': 'Nordeste',
'RN': 'Nordeste',
'PB': 'Nordeste',
'PE': 'Nordeste',
'AL': 'Nordeste',
'SE': 'Nordeste',
'BA': 'Nordeste',
'MG': 'Sudeste',
'ES': 'Sudeste',
'RJ': 'Sudeste',
'SP': 'Sudeste',
'PR': 'Sul',
'SC': 'Sul',
'RS': 'Sul',
'MS': 'Centro-Oeste',
'MT': 'Centro-Oeste',
'GO': 'Centro-Oeste',
'DF': 'Centro-Oeste',
'ZZ': 'Exterior'}

In [16]:
dados['regiao'] = dados.estado.map(regiao)

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\3614364193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['regiao'] = dados.estado.map(regiao)

In [17]:
dados

     estado   municipio_0  votos_Bolsonaro  votos_Haddad    regiao
0        AC    ACRELÂNDIA             5165          1300     Norte
1        AC  ASSIS BRASIL             2333          1660     Norte
2        AC     BRASILÉIA             8711          3208     Norte
3        AC        BUJARI             4676          1274     Norte
4        AC      CAPIXABA             3895          1086     Norte
...     ...           ...              ...           ...       ...
5703     ZZ    WELLINGTON              179           128  Exterior
5704     ZZ      WINDHOEK               11             7  Exterior
5705     ZZ        XANGAI              151            48  Exterior
5706     ZZ        ZAGREB                8             5  Exterior
5707     ZZ       ZURIQUE             2948          1835  Exterior

[5708 rows x 5 columns]

In [18]:
dados.describe(include='all')

       estado   municipio_0  votos_Bolsonaro  votos_Haddad    regiao
count    5708          5708     5.708000e+03  5.708000e+03      5708
unique     28          5425              NaN           NaN         6
top        MG  SÃO DOMINGOS              NaN           NaN  Nordeste
freq      853             6              NaN           NaN      1794
mean      NaN           NaN     1.012576e+04  8.241224e+03       NaN
std       NaN           NaN     6.719347e+04  4.353046e+04       NaN
min       NaN           NaN     5.000000e+00  0.000000e+00       NaN
25%       NaN           NaN     1.103500e+03  1.412750e+03       NaN
50%       NaN           NaN     2.216000e+03  3.014000e+03       NaN
75%       NaN           NaN     5.412000e+03  6.824000e+03       NaN
max       NaN           NaN     3.694834e+06  2.424125e+06       NaN

In [19]:
dados = dados[['regiao','estado','municipio_0','votos_Bolsonaro','votos_Haddad']].sort_values(by='municipio_0')
dados

            regiao estado          municipio_0  votos_Bolsonaro  votos_Haddad
882   Centro-Oeste     GO      ABADIA DE GOIÁS             4285          1928
1345       Sudeste     MG  ABADIA DOS DOURADOS             2117          1821
883   Centro-Oeste     GO            ABADIÂNIA             5204          1781
2418         Norte     PA           ABAETETUBA            19896         61646
1346       Sudeste     MG               ABAETÉ             7581          4289
...            ...    ...                  ...              ...           ...
4415           Sul     RS                ÁUREA             1484          1008
3592           Sul     PR               ÂNGULO             1378           578
618       Nordeste     BA        ÉRICO CARDOSO             1128          4018
2561         Norte     PA               ÓBIDOS             6781         16517
5430       Sudeste     SP                 ÓLEO             1351           382

[5708 rows x 5 columns]

In [20]:
import unicodedata

In [21]:
for i in range(len(dados.municipio_0)):
    dados.municipio_0[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', dados.municipio_0[i]) 
        if not unicodedata.combining(ch))

dados

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\177252174.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.municipio_0[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', dados.municipio_0[i])

            regiao estado          municipio_0  votos_Bolsonaro  votos_Haddad
882   Centro-Oeste     GO      ABADIA DE GOIAS             4285          1928
1345       Sudeste     MG  ABADIA DOS DOURADOS             2117          1821
883   Centro-Oeste     GO            ABADIANIA             5204          1781
2418         Norte     PA           ABAETETUBA            19896         61646
1346       Sudeste     MG               ABAETE             7581          4289
...            ...    ...                  ...              ...           ...
4415           Sul     RS                AUREA             1484          1008
3592           Sul     PR               ANGULO             1378           578
618       Nordeste     BA        ERICO CARDOSO             1128          4018
2561         Norte     PA               OBIDOS             6781         16517
5430       Sudeste     SP                 OLEO             1351           382

[5708 rows x 5 columns]

# Corrigir 
Na planilha eleicao18  mapear

corretor = list(['AREZ',
  'TABOCAO',
  'QUIJINGUE'
])

trocas = list(['ARES'
  'FORTALEZA DO TABOCAO'
  'QUINJINGUE'
])

In [22]:
corretor = list(['AREZ',
  'TABOCAO',
  'QUIJINGUE'
])

trocas = list(['ARES',
  'FORTALEZA DO TABOCAO',
  'QUINJINGUE'
])

In [23]:
dados['municipio'] = dados['municipio_0']

In [24]:
for i in range(len(dados['municipio_0'])):
    if dados['municipio_0'][i] in trocas:
        for k in range(len(trocas)):
            if dados['municipio_0'][i] == trocas[k]:
               dados['municipio'][i] = corretor[k]
    else:
        dados['municipio'][i] = dados['municipio_0'][i]

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\705616213.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['municipio'][i] = dados['municipio_0'][i]
C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105884\705616213.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['municipio'][i] = corretor[k]

In [25]:
dados = dados.drop(columns=['municipio_0'])
dados = dados[['regiao','estado','municipio','votos_Bolsonaro', 'votos_Haddad']]

In [26]:
dados = dados.sort_values(by='municipio')

In [27]:
dados.to_csv('arquivos/eleicao18.csv', index=False)