In [1]:
import pandas as pd
import numpy as np

In [2]:
dadosJair = pd.read_csv('DADOS/TSE/2022_Bolsonaro.csv', sep=';')
dadosLula = pd.read_csv('DADOS/TSE/2022_Lula.csv', sep=';')

In [3]:
dadosJair

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,5317
1,AC,ASSIS BRASIL,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,2717
2,AC,BRASILÉIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,9593
3,AC,BUJARI,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,4693
4,AC,CAPIXABA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,3963
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746,ZZ,WINDHOEK,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,31
5747,ZZ,XANGAI,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,62
5748,ZZ,YANGON,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,0
5749,ZZ,ZAGREB,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,15
5750,ZZ,ZURIQUE,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,2,Não Eleito,2022-10-31 00:28:52,BR,280001618036,Válido,2040602022,2762

In [4]:
dadosLula

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,dt_ult_totalizacao,sg_ue,sq_candidato,nm_tipo_destinacao_votos,sq_eleicao_divulga,qt_votos_nom_validos
0,AC,ACRELÂNDIA,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,1460
1,AC,ASSIS BRASIL,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,1895
2,AC,BRASILÉIA,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,3958
3,AC,BUJARI,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,1958
4,AC,CAPIXABA,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,1497
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5746,ZZ,WINDHOEK,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,4
5747,ZZ,XANGAI,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,125
5748,ZZ,YANGON,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,0
5749,ZZ,ZAGREB,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,26
5750,ZZ,ZURIQUE,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,(PT/PC do B/PV) / SOLIDARIEDADE / (PSOL/REDE) ...,2,Eleito,2022-10-31 00:28:52,BR,280001607829,Válido,2040602022,3189

In [5]:
verificador = dadosLula.describe().qt_votos_nom_validos

In [6]:
dadosJair.columns

Index(['sg_uf', 'nm_municipio', 'cd_cargo', 'ds_cargo', 'nr_candidato',
       'nm_candidato', 'nm_urna_candidato', 'sg_partido',
       'ds_composicao_coligacao', 'nr_turno', 'ds_sit_totalizacao',
       'dt_ult_totalizacao', 'sg_ue', 'sq_candidato',
       'nm_tipo_destinacao_votos', 'sq_eleicao_divulga',
       'qt_votos_nom_validos'],
      dtype='object')

In [7]:
dados = dadosJair[['sg_uf', 'nm_municipio', 'qt_votos_nom_validos']]

In [8]:
dados.columns = ['estado', 'municipio', 'votos_Bolsonaro']

In [9]:
dados['votos_Lula'] = 0
dados

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105544\4109365797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['votos_Lula'] = 0

     estado     municipio  votos_Bolsonaro  votos_Lula
0        AC    ACRELÂNDIA             5317           0
1        AC  ASSIS BRASIL             2717           0
2        AC     BRASILÉIA             9593           0
3        AC        BUJARI             4693           0
4        AC      CAPIXABA             3963           0
...     ...           ...              ...         ...
5746     ZZ      WINDHOEK               31           0
5747     ZZ        XANGAI               62           0
5748     ZZ        YANGON                0           0
5749     ZZ        ZAGREB               15           0
5750     ZZ       ZURIQUE             2762           0

[5751 rows x 4 columns]

In [10]:
for i in range(dadosLula.shape[0]):
    if dados.estado[i] == dadosLula.sg_uf[i]:
        dados.votos_Lula[i] = (dadosLula.qt_votos_nom_validos[i])

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105544\3441732095.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.votos_Lula[i] = (dadosLula.qt_votos_nom_validos[i])

In [11]:
dados

     estado     municipio  votos_Bolsonaro  votos_Lula
0        AC    ACRELÂNDIA             5317        1460
1        AC  ASSIS BRASIL             2717        1895
2        AC     BRASILÉIA             9593        3958
3        AC        BUJARI             4693        1958
4        AC      CAPIXABA             3963        1497
...     ...           ...              ...         ...
5746     ZZ      WINDHOEK               31           4
5747     ZZ        XANGAI               62         125
5748     ZZ        YANGON                0           0
5749     ZZ        ZAGREB               15          26
5750     ZZ       ZURIQUE             2762        3189

[5751 rows x 4 columns]

In [12]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5751 entries, 0 to 5750
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   estado           5751 non-null   object
 1   municipio        5751 non-null   object
 2   votos_Bolsonaro  5751 non-null   int64
 3   votos_Lula       5751 non-null   int64
dtypes: int64(2), object(2)
memory usage: 179.8+ KB

In [13]:
dados.describe().votos_Lula == verificador

count    True
mean     True
std      True
min      True
25%      True
50%      True
75%      True
max      True
dtype: bool

In [14]:
dados['regiao'] = ''

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105544\1577613325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['regiao'] = ''

In [15]:
regiao = {'RO':	'Norte',
'AC': 'Norte',
'AM': 'Norte',
'RR': 'Norte',
'PA': 'Norte',
'AP': 'Norte',
'TO': 'Norte',
'MA': 'Nordeste',
'PI': 'Nordeste',
'CE': 'Nordeste',
'RN': 'Nordeste',
'PB': 'Nordeste',
'PE': 'Nordeste',
'AL': 'Nordeste',
'SE': 'Nordeste',
'BA': 'Nordeste',
'MG': 'Sudeste',
'ES': 'Sudeste',
'RJ': 'Sudeste',
'SP': 'Sudeste',
'PR': 'Sul',
'SC': 'Sul',
'RS': 'Sul',
'MS': 'Centro-Oeste',
'MT': 'Centro-Oeste',
'GO': 'Centro-Oeste',
'DF': 'Centro-Oeste',
'ZZ': 'Exterior'}

In [16]:
dados['regiao'] = dados.estado.map(regiao)

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105544\3614364193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['regiao'] = dados.estado.map(regiao)

In [17]:
dados

     estado     municipio  votos_Bolsonaro  votos_Lula    regiao
0        AC    ACRELÂNDIA             5317        1460     Norte
1        AC  ASSIS BRASIL             2717        1895     Norte
2        AC     BRASILÉIA             9593        3958     Norte
3        AC        BUJARI             4693        1958     Norte
4        AC      CAPIXABA             3963        1497     Norte
...     ...           ...              ...         ...       ...
5746     ZZ      WINDHOEK               31           4  Exterior
5747     ZZ        XANGAI               62         125  Exterior
5748     ZZ        YANGON                0           0  Exterior
5749     ZZ        ZAGREB               15          26  Exterior
5750     ZZ       ZURIQUE             2762        3189  Exterior

[5751 rows x 5 columns]

In [18]:
dados.describe(include='all')

       estado     municipio  votos_Bolsonaro    votos_Lula    regiao
count    5751          5751     5.751000e+03  5.751000e+03      5751
unique     28          5466              NaN           NaN         6
top        MG  SÃO DOMINGOS              NaN           NaN  Nordeste
freq      853             6              NaN           NaN      1794
mean      NaN           NaN     1.012108e+04  1.049313e+04       NaN
std       NaN           NaN     6.017894e+04  6.265559e+04       NaN
min       NaN           NaN     0.000000e+00  0.000000e+00       NaN
25%       NaN           NaN     1.248000e+03  1.765000e+03       NaN
50%       NaN           NaN     2.454000e+03  3.615000e+03       NaN
75%       NaN           NaN     5.834500e+03  8.035000e+03       NaN
max       NaN           NaN     3.191484e+06  3.677921e+06       NaN

In [19]:
dados = dados[['regiao','estado','municipio','votos_Bolsonaro','votos_Lula']].sort_values(by='municipio')
dados

            regiao estado            municipio  votos_Bolsonaro  votos_Lula
882   Centro-Oeste     GO      ABADIA DE GOIÁS             5394        3814
1345       Sudeste     MG  ABADIA DOS DOURADOS             2160        2351
883   Centro-Oeste     GO            ABADIÂNIA             5759        2774
2418         Norte     PA           ABAETETUBA            25118       72313
1346       Sudeste     MG               ABAETÉ             7696        6302
...            ...    ...                  ...              ...         ...
4415           Sul     RS                ÁUREA             1634        1084
3592           Sul     PR               ÂNGULO             1437         729
618       Nordeste     BA        ÉRICO CARDOSO             1175        4915
2561         Norte     PA               ÓBIDOS             8577       19876
5430       Sudeste     SP                 ÓLEO             1163         671

[5751 rows x 5 columns]

In [20]:
import unicodedata

In [21]:

for i in range(len(dados.municipio)):
    dados.municipio[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', dados.municipio[i]) 
        if not unicodedata.combining(ch))

C:\Users\T-GAMER\AppData\Local\Temp\ipykernel_105544\830634456.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados.municipio[i] = ''.join(ch for ch in unicodedata.normalize('NFKD', dados.municipio[i])

In [22]:
dados = dados.sort_values(by='municipio')

In [23]:
dados.to_csv('arquivos/eleicao22.csv', index=False)