In [1]:
import pandas as pd
import numpy as np

In [2]:
n_covid = pd.read_csv('arquivos/covid_municipios.csv')
n_eleicao18 = pd.read_csv('arquivos/eleicao18.csv')
n_eleicao22 = pd.read_csv('arquivos/eleicao22.csv')

In [3]:
n_covid['municipio_estado'] = n_covid['municipio'] + ' / ' + n_covid['estado']
n_eleicao18['municipio_estado'] = n_eleicao18['municipio'] + ' / ' + n_eleicao18['estado']
n_eleicao22['municipio_estado'] = n_eleicao22['municipio'] + ' / ' + n_eleicao22['estado']

In [4]:
n_eleicao18 = n_eleicao18[n_eleicao18['estado'] != 'ZZ']
n_eleicao22 = n_eleicao22[n_eleicao22['estado'] != 'ZZ']

In [5]:
n_covid = n_covid.sort_values(by='municipio_estado')
n_covid.reset_index(inplace=True, drop=True)

n_eleicao18 = n_eleicao18.sort_values(by='municipio_estado')
n_eleicao18.reset_index(inplace=True, drop=True)

n_eleicao22 = n_eleicao22.sort_values(by='municipio_estado')
n_eleicao22.reset_index(inplace=True, drop=True)

In [6]:
n_covid.head(2)

,regiao,estado,municipio,populacao,casosAcumulado,obitosAcumulado,municipio_estado
0,Centro-Oeste,GO,ABADIA DE GOIAS,8773,4013,49,ABADIA DE GOIAS / GO
1,Sudeste,MG,ABADIA DOS DOURADOS,6989,1941,20,ABADIA DOS DOURADOS / MG

In [7]:
n_eleicao18.head(2)

,regiao,estado,municipio,votos_Bolsonaro,votos_Haddad,municipio_estado
0,Centro-Oeste,GO,ABADIA DE GOIAS,4285,1928,ABADIA DE GOIAS / GO
1,Sudeste,MG,ABADIA DOS DOURADOS,2117,1821,ABADIA DOS DOURADOS / MG

In [8]:
n_eleicao22.head(2)

,regiao,estado,municipio,votos_Bolsonaro,votos_Lula,municipio_estado
0,Centro-Oeste,GO,ABADIA DE GOIAS,5394,3814,ABADIA DE GOIAS / GO
1,Sudeste,MG,ABADIA DOS DOURADOS,2160,2351,ABADIA DOS DOURADOS / MG

In [9]:
eleicoes = pd.merge(n_eleicao18, n_eleicao22[['municipio_estado','votos_Bolsonaro','votos_Lula']], on='municipio_estado')

In [10]:
eleicoes

,regiao,estado,municipio,votos_Bolsonaro_x,votos_Haddad,municipio_estado,votos_Bolsonaro_y,votos_Lula
0,Centro-Oeste,GO,ABADIA DE GOIAS,4285,1928,ABADIA DE GOIAS / GO,5394,3814
1,Sudeste,MG,ABADIA DOS DOURADOS,2117,1821,ABADIA DOS DOURADOS / MG,2160,2351
2,Centro-Oeste,GO,ABADIANIA,5204,1781,ABADIANIA / GO,5759,2774
3,Sudeste,MG,ABAETE,7581,4289,ABAETE / MG,7696,6302
4,Norte,PA,ABAETETUBA,19896,61646,ABAETETUBA / PA,25118,72313
...,...,...,...,...,...,...,...,...
5565,Nordeste,BA,XIQUE-XIQUE,4804,18982,XIQUE-XIQUE / BA,5629,20301
5566,Nordeste,PB,ZABELE,247,1285,ZABELE / PB,241,1529
5567,Sudeste,SP,ZACARIAS,1132,457,ZACARIAS / SP,1116,720
5568,Nordeste,MA,ZE DOCA,4658,17495,ZE DOCA / MA,6313,17461
5569,Sul,SC,ZORTEA,1368,727,ZORTEA / SC,1473,1053

In [11]:
combinados = pd.merge(n_covid, eleicoes[['municipio_estado','votos_Bolsonaro_x','votos_Haddad','votos_Bolsonaro_y','votos_Lula']], on='municipio_estado')

In [12]:
combinados

,regiao,estado,municipio,populacao,casosAcumulado,obitosAcumulado,municipio_estado,votos_Bolsonaro_x,votos_Haddad,votos_Bolsonaro_y,votos_Lula
0,Centro-Oeste,GO,ABADIA DE GOIAS,8773,4013,49,ABADIA DE GOIAS / GO,4285,1928,5394,3814
1,Sudeste,MG,ABADIA DOS DOURADOS,6989,1941,20,ABADIA DOS DOURADOS / MG,2117,1821,2160,2351
2,Centro-Oeste,GO,ABADIANIA,20042,2199,55,ABADIANIA / GO,5204,1781,5759,2774
3,Sudeste,MG,ABAETE,23237,4246,48,ABAETE / MG,7581,4289,7696,6302
4,Norte,PA,ABAETETUBA,157698,11868,243,ABAETETUBA / PA,19896,61646,25118,72313
...,...,...,...,...,...,...,...,...,...,...,...
5565,Nordeste,BA,XIQUE-XIQUE,46483,3406,100,XIQUE-XIQUE / BA,4804,18982,5629,20301
5566,Nordeste,PB,ZABELE,2240,314,1,ZABELE / PB,247,1285,241,1529
5567,Sudeste,SP,ZACARIAS,2718,282,12,ZACARIAS / SP,1132,457,1116,720
5568,Nordeste,MA,ZE DOCA,51714,6203,76,ZE DOCA / MA,4658,17495,6313,17461
5569,Sul,SC,ZORTEA,3363,1418,14,ZORTEA / SC,1368,727,1473,1053

In [13]:
combinados.columns = ['regiao', 'estado', 'municipio', 'populacao', 'casosAcumulado',
       'obitosAcumulado', 'municipio_estado', 'votos_Bolsonaro_18',
       'votos_Haddad', 'votos_Bolsonaro_22', 'votos_Lula']

In [14]:
nome_dos_estados = {
'GO': 'Goiás',
'MG' : 'Minas Gerais',
'PA' : 'Pará',
'CE' : 'Ceará',
'BA' : 'Bahia',
'PR' : 'Paraná ',
'SC' : 'Santa Catarina',
'PE' : 'Pernambuco',
'TO' : 'Tocantins',
'MA' : 'Maranhão',
'RN' : 'Rio Grande do Norte',
'PI' : 'Piauí',
'RS' : 'Rio Grande do Sul',
'MT' : 'Mato Grosso',
'AC' : 'Acre',
'SP' : 'São Paulo',
'ES' : 'Espírito Santo',
'AL' : 'Alagoas',
'PB' : 'Paraíba',
'MS' : 'Mato Grosso do Sul',
'RO' : 'Rondônia',
'RR' : 'Roraima',
'AM' : 'Amazonas',
'AP' : 'Amapá',
'SE' : 'Sergipe',
'RJ' : 'Rio de Janeiro',
'DF' : 'Distrito Federal'}

In [15]:
combinados['estado_nome'] = combinados.estado.map(nome_dos_estados)

In [16]:
combinados['ISO_code'] = 'BR-' + combinados.estado

In [17]:
combinados

,regiao,estado,municipio,populacao,casosAcumulado,obitosAcumulado,municipio_estado,votos_Bolsonaro_18,votos_Haddad,votos_Bolsonaro_22,votos_Lula,estado_nome,ISO_code
0,Centro-Oeste,GO,ABADIA DE GOIAS,8773,4013,49,ABADIA DE GOIAS / GO,4285,1928,5394,3814,Goiás,BR-GO
1,Sudeste,MG,ABADIA DOS DOURADOS,6989,1941,20,ABADIA DOS DOURADOS / MG,2117,1821,2160,2351,Minas Gerais,BR-MG
2,Centro-Oeste,GO,ABADIANIA,20042,2199,55,ABADIANIA / GO,5204,1781,5759,2774,Goiás,BR-GO
3,Sudeste,MG,ABAETE,23237,4246,48,ABAETE / MG,7581,4289,7696,6302,Minas Gerais,BR-MG
4,Norte,PA,ABAETETUBA,157698,11868,243,ABAETETUBA / PA,19896,61646,25118,72313,Pará,BR-PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,Nordeste,BA,XIQUE-XIQUE,46483,3406,100,XIQUE-XIQUE / BA,4804,18982,5629,20301,Bahia,BR-BA
5566,Nordeste,PB,ZABELE,2240,314,1,ZABELE / PB,247,1285,241,1529,Paraíba,BR-PB
5567,Sudeste,SP,ZACARIAS,2718,282,12,ZACARIAS / SP,1132,457,1116,720,São Paulo,BR-SP
5568,Nordeste,MA,ZE DOCA,51714,6203,76,ZE DOCA / MA,4658,17495,6313,17461,Maranhão,BR-MA
5569,Sul,SC,ZORTEA,3363,1418,14,ZORTEA / SC,1368,727,1473,1053,Santa Catarina,BR-SC

In [18]:
combinados.to_csv('arquivos/dados_looker.csv', index=False)